// Environment Configuration for Manila Guide (Local Development)
// For production, this file is generated by scripts/generate-env.js

window.__ENV = {
  // Supabase Configuration
  SUPABASE_URL: "https://ljsoibbebuxbtczmfdag.supabase.co",
  SUPABASE_ANON_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqc29pYmJlYnV4YnRjem1mZGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MDY5MDgsImV4cCI6MjA5MzE4MjkwOH0.fqZxyaOf95WTcCdnTyOQy19l-AGOUylUibsgaAHuEWw",
  SUPABASE_PUBLISHABLE_KEY: "b_publishable_U2SoRHdvqXuU9p9qSNJRkw_N5GqnZgR",

  // Google Maps Configuration
  GOOGLE_MAPS_KEY: "AIzaSyD8CPngkZlmt6DcW9llc6nuCk8SNX_ToQo",

  // Mistral API Keys
  MISTRAL_API_KEYS: "",
};

// Extended config for frontend features
window.CONFIG = {
  // Application Settings
  APP_NAME: "Manila Guide",
  APP_TAGLINE: "Tourist Information System",

  // Feature Flags
  ENABLE_REGISTRATION: true,
  ENABLE_ADMIN_ACCESS: true,
  REQUIRE_EMAIL_VERIFICATION: true,

  // UI Configuration
  MIN_PASSWORD_LENGTH: 6,
  SESSION_TIMEOUT_MINUTES: 120,

  // Development Settings
  IS_DEVELOPMENT: true,
  DEBUG_MODE: true,
};
